### ISSUE TITLE
[Error] This content isn't available

### ISSUE THREAD

**Issue by BrightDV** [lighttube-org/LightTube#131]
### Describe what happened

Video playback does not work.

### Instance URL

https://tube.kuylar.dev

### LightTube & InnerTube versions

v2024.2.20 / ?

### Resource path

https://tube.kuylar.dev/watch?v=h04_4Msuw2k

### Language & region

fr_FR

### Stack trace

None, returns a 200.

### Notes

This issue happened to invidious too, see [this issue](https://github.com/iv-org/invidious/issues/3822).
YouTube may have started to block your instance :/
The video plays fine on these instances, however:
- [tube.instellate.xyz](https://tube.instellate.xyz/)
- [lighttube.plerx.de](https://lighttube.plerx.de/)

![image](https://github.com/lighttube-org/LightTube/assets/92821484/9ce692c4-7412-41e8-ab92-9072e609a861)

**Comment by kuylar** [comment]
Looks like a YouTube block, fixed in `tube.kuylar.dev`

For the instance hosters in future: check out [Invidious' Smart IPv6 Rotator script](https://docs.invidious.io/ipv6-rotator)

Leaving this issue up until we add a check for the video ID in YouTube's response

**Comment by BrightDV** [comment]
Thanks for the fast fix!

**Comment by BrightDV** [comment]
Hello,
New blocking round from YouTube:
![image](https://github.com/lighttube-org/LightTube/assets/92821484/9da7fa98-48a0-49e0-b96d-92da3c195c7c)

Your instance, LightTube v2024.3.9, url: https://tube.kuylar.dev/watch?v=UDVtMYqUAyw

Maybe useful:
NewPipe workaround (used by Invidious): https://github.com/TeamNewPipe/NewPipe/issues/8713#issuecomment-1207443550

**Comment by kuylar** [comment]
This is a different issue, but I will keep it here since both of them can be fixed with the same update.

Been working on this for the past day and I cant find a good way of beating this, as now they require a PoToken from Google Play Services (source: https://github.com/ReVanced/revanced-patches/issues/2878 ). YouTube hit us very hard this time.

This leaves us to either:
- use `clientName: IOS`, but that lacks a lot of `adaptiveFormats` (used by DASH playback, which we don't use but show in the download dialog), and most importantly, the `formats` field, which we **need** for compatibility mode, or
- use the formats from `clientName: WEB`, which would be good, but unfortunately, that requires us to parse the player JavaScript from YouTube to solve 2 challenges.  Since Invidious, NewPipeExtractor and yt-dlp were already doing this from the beginning, they can just fall back to the WEB client with an update. (here's yt-dlp doing it: https://github.com/yt-dlp/yt-dlp/pull/9553)

I am currently working on implementing the latter, and I'd say that I'm 70% the way there (one out of two challenges solved) and the only thing that remains is now to make the playback URLs not throttle to 60-70kbps, which is where running the JavaScript comes in.

This update *will* take some time. In the meantime, disable compatibility mode in settings, as HLS playback isn't affected (as it uses the iOS client instead of android)

> [!NOTE]
> unfortunately, because of #133, you'll have to paste the following into your browser's JavaScript console to turn off compatibility mode. *sorry*
> ```js
> document.cookie = "compatibility=false; path=/;"
> ```

**Comment by epman100** [comment]
> Hello, New blocking round from YouTube, [other frontends are also blocked](https://github.com/iv-org/invidious/issues/4498): 

new variants of that problem [here](https://github.com/iv-org/invidious/issues/4584) & [here](https://github.com/iv-org/invidious/issues/4653)

those are not affected by LightTube

**Comment by kuylar** [comment]
Wrong, normal formats (and also the download links) are blocked. lighttube-org/InnerTube#45 fixes this in the long term by not using the ANDROID client, but merging that to master will take some time. A fix will be up in https://tube-nightly.kuylar.dev in a week or two

**Comment by Chirunos** [comment]
I'm getting 'This video is unavailable' 'Watch on the latest version of YouTube.' for any video in all working officially listed instances on all major browsers. Is this related to this issue?

![image](https://github.com/user-attachments/assets/e7e24454-2d37-4729-8749-6cda4132a7d3)

**Comment by Chirunos** [comment]
Not getting this anymore with the latest nightly
